global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'yourgmail@gmail.com'
  smtp_auth_username: 'yourgmail@gmail.com'
  smtp_auth_password: 'apppassword'

route:
  receiver: 'gmail-alert'
  repeat_interval: 10m

receivers:
  - name: 'gmail-alert'
    email_configs:
      - to: 'yourgmail@gmail.com'
        send_resolved: true